export const data = [
  { state: "Alaska", district: "00" },
  { state: "Montana", district: "00" },
  { state: "Wyoming", district: "00" },
  { state: "South Dakota", district: "00" },
  { state: "New Mexico", district: "2" },
  { state: "Oregon", district: "2" },
  { state: "North Dakota", district: "00" },
  { state: "Nebraska", district: "3" },
  { state: "Texas", district: "23" },
  { state: "Nevada", district: "2" },
  { state: "Arizona", district: "1" },
  { state: "Kansas", district: "1" },
  { state: "Nevada", district: "4" },
  { state: "Colorado", district: "3" },
  { state: "New Mexico", district: "3" },
  { state: "Idaho", district: "2" },
  { state: "Utah", district: "2" },
  { state: "Idaho", district: "1" },
  { state: "Texas", district: "13" },
  { state: "Colorado", district: "4" },
  { state: "Oklahoma", district: "3" },
  { state: "Minnesota", district: "7" },
  { state: "Arizona", district: "4" },
  { state: "California", district: "8" },
  { state: "California", district: "1" },
  { state: "Minnesota", district: "8" },
  { state: "Texas", district: "11" },
  { state: "Maine", district: "2" },
  { state: "Texas", district: "19" },
  { state: "Michigan", district: "1" },
  { state: "Wisconsin", district: "7" },
  { state: "Iowa", district: "4" },
  { state: "Arkansas", district: "4" },
  { state: "Oklahoma", district: "2" },
  { state: "Utah", district: "3" },
  { state: "Missouri", district: "8" },
  { state: "Utah", district: "1" },
  { state: "Arkansas", district: "1" },
  { state: "Washington", district: "4" },
  { state: "Missouri", district: "6" },
  { state: "Oregon", district: "4" },
  { state: "Arizona", district: "3" },
  { state: "Mississippi", district: "2" },
  { state: "Washington", district: "5" },
  { state: "New York", district: "21" },
  { state: "Illinois", district: "15" },
  { state: "Louisiana", district: "5" },
  { state: "Missouri", district: "4" },
  { state: "Kansas", district: "4" },
  { state: "Kansas", district: "2" },
  { state: "California", district: "2" },
  { state: "California", district: "4" },
  { state: "Mississippi", district: "3" },
  { state: "Louisiana", district: "4" },
  { state: "Iowa", district: "2" },
  { state: "Kentucky", district: "1" },
  { state: "Iowa", district: "1" },
  { state: "Minnesota", district: "1" },
  { state: "Kentucky", district: "5" },
  { state: "Wisconsin", district: "3" },
  { state: "Mississippi", district: "1" },
  { state: "Illinois", district: "18" },
  { state: "Alabama", district: "7" },
  { state: "Alabama", district: "2" },
  { state: "Texas", district: "4" },
  { state: "Virginia", district: "5" },
  { state: "California", district: "23" },
  { state: "Pennsylvania", district: "12" },
  { state: "Oklahoma", district: "4" },
  { state: "West Virginia", district: "3" },
  { state: "Pennsylvania", district: "15" },
  { state: "Georgia", district: "2" },
  { state: "Texas", district: "28" },
  { state: "Vermont", district: "00" },
  { state: "Tennessee", district: "7" },
  { state: "Texas", district: "27" },
  { state: "Washington", district: "3" },
  { state: "Virginia", district: "9" },
  { state: "Alabama", district: "4" },
  { state: "Nebraska", district: "1" },
  { state: "Iowa", district: "3" },
  { state: "Georgia", district: "8" },
  { state: "Florida", district: "2" },
  { state: "Michigan", district: "4" },
  { state: "Texas", district: "34" },
  { state: "Georgia", district: "12" },
  { state: "South Carolina", district: "6" },
  { state: "Mississippi", district: "4" },
  { state: "West Virginia", district: "2" },
  { state: "Georgia", district: "1" },
  { state: "New York", district: "19" },
  { state: "Illinois", district: "16" },
  { state: "Texas", district: "1" },
  { state: "Arizona", district: "2" },
  { state: "North Carolina", district: "3" },
  { state: "Texas", district: "15" },
  { state: "Texas", district: "17" },
  { state: "Texas", district: "25" },
  { state: "Alabama", district: "3" },
  { state: "Colorado", district: "2" },
  { state: "New York", district: "23" },
  { state: "Washington", district: "8" },
  { state: "Florida", district: "3" },
  { state: "Colorado", district: "5" },
  { state: "Indiana", district: "8" },
  { state: "Ohio", district: "6" },
  { state: "Kentucky", district: "2" },
  { state: "Texas", district: "36" },
  { state: "Georgia", district: "10" },
  { state: "Louisiana", district: "3" },
  { state: "Illinois", district: "17" },
  { state: "Washington", district: "6" },
  { state: "California", district: "24" },
  { state: "Missouri", district: "3" },
  { state: "Tennessee", district: "8" },
  { state: "North Carolina", district: "11" },
  { state: "Wisconsin", district: "8" },
  { state: "California", district: "21" },
  { state: "New Hampshire", district: "2" },
  { state: "Tennessee", district: "6" },
  { state: "Florida", district: "17" },
  { state: "Indiana", district: "4" },
  { state: "West Virginia", district: "1" },
  { state: "Missouri", district: "7" },
  { state: "Hawaii", district: "2" },
  { state: "Indiana", district: "6" },
  { state: "Washington", district: "1" },
  { state: "California", district: "3" },
  { state: "North Carolina", district: "7" },
  { state: "Alabama", district: "1" },
  { state: "Texas", district: "8" },
  { state: "Tennessee", district: "4" },
  { state: "Pennsylvania", district: "13" },
  { state: "Virginia", district: "6" },
  { state: "Texas", district: "21" },
  { state: "California", district: "36" },
  { state: "Illinois", district: "13" },
  { state: "Ohio", district: "5" },
  { state: "South Carolina", district: "5" },
  { state: "North Carolina", district: "1" },
  { state: "Arkansas", district: "3" },
  { state: "South Carolina", district: "7" },
  { state: "South Carolina", district: "3" },
  { state: "Georgia", district: "9" },
  { state: "Oregon", district: "5" },
  { state: "New York", district: "22" },
  { state: "Texas", district: "10" },
  { state: "Texas", district: "5" },
  { state: "Illinois", district: "12" },
  { state: "Arkansas", district: "2" },
  { state: "Wisconsin", district: "6" },
  { state: "California", district: "20" },
  { state: "California", district: "51" },
  { state: "Ohio", district: "15" },
  { state: "Ohio", district: "4" },
  { state: "New Mexico", district: "1" },
  { state: "Tennessee", district: "3" },
  { state: "Wisconsin", district: "2" },
  { state: "North Carolina", district: "8" },
  { state: "Indiana", district: "9" },
  { state: "Kentucky", district: "4" },
  { state: "Virginia", district: "4" },
  { state: "Kentucky", district: "6" },
  { state: "Michigan", district: "7" },
  { state: "Indiana", district: "3" },
  { state: "Alabama", district: "6" },
  { state: "Tennessee", district: "1" },
  { state: "Michigan", district: "10" },
  { state: "Louisiana", district: "6" },
  { state: "Louisiana", district: "1" },
  { state: "Florida", district: "1" },
  { state: "Maryland", district: "1" },
  { state: "New York", district: "27" },
  { state: "Indiana", district: "2" },
  { state: "Ohio", district: "7" },
  { state: "Georgia", district: "3" },
  { state: "Virginia", district: "1" },
  { state: "Alabama", district: "5" },
  { state: "North Carolina", district: "6" },
  { state: "Georgia", district: "14" },
  { state: "North Carolina", district: "5" },
  { state: "Michigan", district: "6" },
  { state: "Puerto Rico", district: "00" },

  { state: "Pennsylvania", district: "16" },
  { state: "Pennsylvania", district: "9" },
  { state: "Maine", district: "1" },
  { state: "Michigan", district: "2" },
  { state: "North Carolina", district: "2" },
  { state: "Florida", district: "25" },
  { state: "Ohio", district: "2" },
  { state: "South Carolina", district: "2" },
  { state: "Oregon", district: "1" },
  { state: "Minnesota", district: "6" },
  { state: "Nevada", district: "3" },
  { state: "Pennsylvania", district: "14" },
  { state: "California", district: "16" },
  { state: "California", district: "50" },
  { state: "Virginia", district: "7" },
  { state: "Pennsylvania", district: "8" },
  { state: "Michigan", district: "3" },
  { state: "North Carolina", district: "10" },
  { state: "Utah", district: "4" },
  { state: "Florida", district: "11" },
  { state: "Florida", district: "6" },
  { state: "New Hampshire", district: "1" },
  { state: "Ohio", district: "8" },
  { state: "Texas", district: "14" },
  { state: "Minnesota", district: "2" },
  { state: "Florida", district: "20" },
  { state: "Missouri", district: "5" },
  { state: "New York", district: "24" },
  { state: "Massachusetts", district: "1" },
  { state: "Michigan", district: "5" },
  { state: "Tennessee", district: "2" },
  { state: "North Carolina", district: "13" },
  { state: "Ohio", district: "12" },
  { state: "Texas", district: "31" },
  { state: "Texas", district: "6" },
  { state: "Florida", district: "26" },
  { state: "New Jersey", district: "2" },
  { state: "Oklahoma", district: "5" },
  { state: "Connecticut", district: "2" },
  { state: "Ohio", district: "14" },
  { state: "Maryland", district: "6" },
  { state: "Delaware", district: "0" },
  { state: "Indiana", district: "5" },
  { state: "Wisconsin", district: "5" },
  { state: "Florida", district: "4" },
  { state: "California", district: "10" },
  { state: "Florida", district: "8" },
  { state: "California", district: "5" },
  { state: "Wisconsin", district: "1" },
  { state: "Florida", district: "9" },
  { state: "California", district: "25" },
  { state: "Oklahoma", district: "1" },
  { state: "Massachusetts", district: "2" },
  { state: "Illinois", district: "14" },
  { state: "South Carolina", district: "1" },
  { state: "Florida", district: "18" },
  { state: "Michigan", district: "8" },
  { state: "Pennsylvania", district: "11" },
  { state: "Maryland", district: "5" },
  { state: "Texas", district: "12" },
  { state: "Virginia", district: "10" },
  { state: "Florida", district: "5" },
  { state: "New York", district: "18" },
  { state: "South Carolina", district: "4" },
  { state: "Louisiana", district: "2" },
  { state: "Tennessee", district: "5" },
  { state: "Connecticut", district: "5" },
  { state: "California", district: "9" },
  { state: "New York", district: "20" },
  { state: "Massachusetts", district: "9" },
  { state: "Ohio", district: "16" },
  { state: "California", district: "22" },
  { state: "Indiana", district: "1" },
  { state: "Ohio", district: "10" },
  { state: "Florida", district: "10" },
  { state: "Illinois", district: "2" },
  { state: "Pennsylvania", district: "10" },
  { state: "Oregon", district: "3" },
  { state: "Georgia", district: "11" },
  { state: "North Carolina", district: "4" },
  { state: "Texas", district: "22" },
  { state: "Washington", district: "2" },
  { state: "Virginia", district: "2" },
  { state: "New Jersey", district: "5" },
  { state: "New Jersey", district: "7" },
  { state: "Virginia", district: "3" },
  { state: "California", district: "26" },
  { state: "California", district: "42" },
  { state: "California", district: "19" },
  { state: "Pennsylvania", district: "6" },
  { state: "Texas", district: "26" },
  { state: "New Jersey", district: "3" },
  { state: "Ohio", district: "13" },
  { state: "Florida", district: "12" },
  { state: "Pennsylvania", district: "17" },
  { state: "Florida", district: "16" },
  { state: "Pennsylvania", district: "7" },
  { state: "Maryland", district: "8" },
  { state: "North Carolina", district: "9" },
  { state: "Washington", district: "10" },
  { state: "Florida", district: "15" },
  { state: "Rhode Island", district: "2" },
  { state: "Massachusetts", district: "3" },
  { state: "Kansas", district: "3" },
  { state: "Florida", district: "19" },
  { state: "Georgia", district: "13" },
  { state: "Texas", district: "16" },
  { state: "California", district: "27" },
  { state: "California", district: "18" },
  { state: "New Jersey", district: "4" },
  { state: "Ohio", district: "1" },
  { state: "Connecticut", district: "1" },
  { state: "Massachusetts", district: "4" },
  { state: "New York", district: "1" },
  { state: "Pennsylvania", district: "1" },
  { state: "Arizona", district: "6" },
  { state: "California", district: "15" },
  { state: "Texas", district: "35" },
  { state: "California", district: "49" },
  { state: "North Carolina", district: "12" },
  { state: "California", district: "7" },
  { state: "Arizona", district: "8" },
  { state: "Minnesota", district: "3" },
  { state: "Massachusetts", district: "6" },
  { state: "Florida", district: "7" },
  { state: "New York", district: "25" },
  { state: "Nebraska", district: "2" },
  { state: "New Jersey", district: "11" },
  { state: "Georgia", district: "4" },
  { state: "California", district: "11" },
  { state: "Maryland", district: "7" },
  { state: "Tennessee", district: "9" },
  { state: "Texas", district: "3" },
  { state: "Pennsylvania", district: "4" },
  { state: "Colorado", district: "6" },
  { state: "Connecticut", district: "3" },
  { state: "Missouri", district: "2" },
  { state: "Ohio", district: "9" },
  { state: "Connecticut", district: "4" },
  { state: "Michigan", district: "11" },
  { state: "New Jersey", district: "12" },
  { state: "Michigan", district: "12" },
  { state: "Georgia", district: "7" },
  { state: "New York", district: "17" },
  { state: "Illinois", district: "6" },
  { state: "Texas", district: "30" },
  { state: "New Jersey", district: "1" },
  { state: "Maryland", district: "2" },
  { state: "Colorado", district: "7" },
  { state: "Minnesota", district: "4" },
  { state: "California", district: "45" },
  { state: "Massachusetts", district: "8" },
  { state: "Kentucky", district: "3" },
  { state: "California", district: "41" },
  { state: "Texas", district: "2" },
  { state: "Maryland", district: "3" },
  { state: "Indiana", district: "7" },
  { state: "Illinois", district: "10" },
  { state: "Georgia", district: "6" },
  { state: "Maryland", district: "4" },
  { state: "Arizona", district: "5" },
  { state: "Pennsylvania", district: "18" },
  { state: "California", district: "33" },
  { state: "Illinois", district: "11" },
  { state: "Rhode Island", district: "1" },
  { state: "California", district: "52" },
  { state: "Florida", district: "14" },
  { state: "Massachusetts", district: "5" },
  { state: "Georgia", district: "5" },
  { state: "Texas", district: "24" },
  { state: "Florida", district: "21" },
  { state: "California", district: "14" },
  { state: "Illinois", district: "1" },
  { state: "New York", district: "3" },
  { state: "Ohio", district: "11" },
  { state: "Illinois", district: "3" },
  { state: "Texas", district: "18" },
  { state: "Ohio", district: "3" },
  { state: "Missouri", district: "1" },
  { state: "New York", district: "26" },
  { state: "California", district: "28" },
  { state: "California", district: "31" },
  { state: "California", district: "47" },
  { state: "New Jersey", district: "6" },
  { state: "Texas", district: "33" },
  { state: "Hawaii", district: "1" },
  { state: "Florida", district: "27" },
  { state: "Illinois", district: "8" },
  { state: "Arizona", district: "7" },
  { state: "California", district: "39" },
  { state: "Texas", district: "20" },
  { state: "Colorado", district: "1" },
  { state: "Texas", district: "29" },
  { state: "Florida", district: "13" },
  { state: "Michigan", district: "14" },
  { state: "Texas", district: "32" },
  { state: "Virginia", district: "11" },
  { state: "California", district: "17" },
  { state: "Michigan", district: "13" },
  { state: "Michigan", district: "9" },
  { state: "Washington", district: "9" },
  { state: "New York", district: "2" },
  { state: "California", district: "6" },
  { state: "Florida", district: "22" },
  { state: "Florida", district: "23" },
  { state: "California", district: "35" },
  { state: "Texas", district: "9" },
  { state: "Arizona", district: "9" },
  { state: "Texas", district: "7" },
  { state: "Virginia", district: "8" },
  { state: "California", district: "48" },
  { state: "Washington", district: "7" },
  { state: "California", district: "30" },
  { state: "Minnesota", district: "5" },
  { state: "California", district: "53" },
  { state: "Wisconsin", district: "4" },
  { state: "California", district: "32" },
  { state: "New York", district: "4" },
  { state: "Florida", district: "24" },
  { state: "Illinois", district: "9" },
  { state: "Nevada", district: "1" },
  { state: "California", district: "38" },
  { state: "California", district: "13" },
  { state: "Illinois", district: "5" },
  { state: "New Jersey", district: "9" },
  { state: "California", district: "29" },
  { state: "California", district: "44" },
  { state: "New York", district: "16" },
  { state: "New Jersey", district: "10" },
  { state: "California", district: "43" },
  { state: "California", district: "46" },
  { state: "New York", district: "11" },
  { state: "Massachusetts", district: "7" },
  { state: "Pennsylvania", district: "2" },
  { state: "Illinois", district: "7" },
  { state: "District of Columbia", district: "00" },
  { state: "California", district: "40" },
  { state: "California", district: "37" },
  { state: "New Jersey", district: "8" },
  { state: "Pennsylvania", district: "3" },
  { state: "Illinois", district: "4" },
  { state: "New York", district: "5" },
  { state: "California", district: "34" },
  { state: "California", district: "12" },
  { state: "New York", district: "6" },
  { state: "New York", district: "8" },
  { state: "New York", district: "14" },
  { state: "New York", district: "7" },
  { state: "New York", district: "9" },
  { state: "New York", district: "12" },
  { state: "New York", district: "15" },
  { state: "New York", district: "10" },
  { state: "New York", district: "13" },
];

const abs = [
  { state: "Alabama", ab: "AL" },
  { state: "Alaska", ab: "AK" },
  { state: "Arizona", ab: "AZ" },
  { state: "Arkansas", ab: "AR" },
  { state: "California", ab: "CA" },
  { state: "Colorado", ab: "CO" },
  { state: "Connecticut", ab: "CT" },
  { state: "Delaware", ab: "DE" },
  { state: "Florida", ab: "FL" },
  { state: "Georgia", ab: "GA" },
  { state: "Hawaii", ab: "HI" },
  { state: "Idaho", ab: "ID" },
  { state: "Illinois", ab: "IL" },
  { state: "Indiana", ab: "IN" },
  { state: "Iowa", ab: "IA" },
  { state: "Kansas", ab: "KS" },
  { state: "Kentucky", ab: "KY" },
  { state: "Louisiana", ab: "LA" },
  { state: "Maine", ab: "ME" },
  { state: "Maryland", ab: "MD" },
  { state: "Massachusetts", ab: "MA" },
  { state: "Michigan", ab: "MI" },
  { state: "Minnesota", ab: "MN" },
  { state: "Mississippi", ab: "MS" },
  { state: "Missouri", ab: "MO" },
  { state: "Montana", ab: "MT" },
  { state: "Guam", ab: "GU" },
  { state: "Nebraska", ab: "NE" },
  { state: "Nevada", ab: "NV" },
  { state: "Puerto Rico", ab: "PR" },
  { state: "New Hampshire", ab: "NH" },
  { state: "New Jersey", ab: "NJ" },
  { state: "New Mexico", ab: "NM" },
  { state: "New York", ab: "NY" },
  { state: "North Carolina", ab: "NC" },
  { state: "North Dakota", ab: "ND" },
  { state: "Ohio", ab: "OH" },
  { state: "Oklahoma", ab: "OK" },
  { state: "Oregon", ab: "OR" },
  { state: "Pennsylvania", ab: "PA" },
  { state: "Rhode Island", ab: "RI" },
  { state: "N. Mariana Islands", ab: "MP" },
  { state: "South Carolina", ab: "SC" },
  { state: "South Dakota", ab: "SD" },
  { state: "Tennessee", ab: "TN" },
  { state: "Texas", ab: "TX" },
  { state: "Utah", ab: "UT" },
  { state: "Vermont", ab: "VT" },
  { state: "Vermont", ab: "VT" },
  { state: "Virginia", ab: "VA" },
  { state: "Washington", ab: "WA" },
  { state: "West Virginia", ab: "WV" },
  { state: "Wisconsin", ab: "WI" },
  { state: "Wyoming", ab: "WY" },
  { state: "Commonwealth/Territory:", ab: "Abbreviation:" },
  { state: "District of Columbia", ab: "DC" },
  { state: "Marshall Islands", ab: "MH" },
  { state: "Military “State”:", ab: "Abbreviation:" },
  { state: "Armed Forces Africa", ab: "AE" },
  { state: "Armed Forces Americas", ab: "AA" },
  { state: "Armed Forces Canada", ab: "AE" },
  { state: "Armed Forces Europe", ab: "AE" },
  { state: "Armed Forces Middle East", ab: "AE" },
  { state: "Armed Forces Pacific", ab: "AP" },
];

console.log(
  JSON.stringify(
    data.map((value) => {
      const ab = abs.find((v) => v.state === value.state);

      return {
        state: ab.ab.toLowerCase(),
        district:
          value.district.length === 1 ? "0" + value.district : value.district,
      };
    })
  )
);
