(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index~scratch"],{

/***/ "./src/components/StoryCard.svelte":
/*!*****************************************!*\
  !*** ./src/components/StoryCard.svelte ***!
  \*****************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* WEBPACK VAR INJECTION */(function(module) {/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte_transition__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte/transition */ "./node_modules/svelte/transition/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var utils_time__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! utils/time */ "./src/utils/time.ts");
/* harmony import */ var utils_time__WEBPACK_IMPORTED_MODULE_3___default = /*#__PURE__*/__webpack_require__.n(utils_time__WEBPACK_IMPORTED_MODULE_3__);
/* harmony import */ var _Users_samueldesota_d_fightforblacklives_fightforblacklives_com_node_modules_svelte_loader_hot_lib_svelte3_hot_api_js__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./node_modules/svelte-loader-hot/lib/svelte3/hot-api.js */ "./node_modules/svelte-loader-hot/lib/svelte3/hot-api.js");
/* harmony import */ var _Users_samueldesota_d_fightforblacklives_fightforblacklives_com_node_modules_svelte_hmr_runtime_proxy_adapter_dom_js__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ./node_modules/svelte-hmr/runtime/proxy-adapter-dom.js */ "./node_modules/svelte-hmr/runtime/proxy-adapter-dom.js");
/* src/components/StoryCard.svelte generated by Svelte v3.23.0 */





const file = "src/components/StoryCard.svelte";

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[10] = list[i];
	return child_ctx;
}

// (72:2) {#if !swapping}
function create_if_block_1(ctx) {
	let h2;
	let t_value = /*profile*/ ctx[2].name + "";
	let t;
	let h2_intro;
	let h2_outro;
	let current;

	const block = {
		c: function create() {
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H2", { class: true });
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, t_value);
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "text-4xl font-bold");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 72, 4, 1648);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, h2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t);
			current = true;
		},
		p: function update(ctx, dirty) {
			if ((!current || dirty & /*profile*/ 4) && t_value !== (t_value = /*profile*/ ctx[2].name + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		i: function intro(local) {
			if (current) return;

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (h2_outro) h2_outro.end(1);

				if (!h2_intro) h2_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(h2, svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"], {
					duration: /*animationDuration*/ ctx[3],
					[/*animationDimension*/ ctx[4]]: -20
				});

				h2_intro.start();
			});

			current = true;
		},
		o: function outro(local) {
			if (h2_intro) h2_intro.invalidate();

			h2_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(h2, svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"], {
				duration: /*animationDuration*/ ctx[3],
				[/*animationDimension*/ ctx[4]]: 20
			});

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(h2);
			if (detaching && h2_outro) h2_outro.end();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(72:2) {#if !swapping}",
		ctx
	});

	return block;
}

// (81:4) {#if !swapping}
function create_if_block(ctx) {
	let p;
	let span0;
	let t0_value = /*field*/ ctx[10].name + "";
	let t0;
	let t1;
	let t2;
	let span1;
	let t3_value = /*profile*/ ctx[2][/*field*/ ctx[10].key] + "";
	let t3;
	let t4;
	let p_intro;
	let p_outro;
	let current;

	const block = {
		c: function create() {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h();
		},
		l: function claim(nodes) {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true });
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ":");
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(p_nodes);
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "SPAN", { class: true });
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, t3_value);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(p_nodes);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "mr-4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 85, 8, 2132);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "text-brown-gray inline-block");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 86, 8, 2180);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p, "class", "text-2xl mt-4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 81, 6, 1938);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, p, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t4);
			current = true;
		},
		p: function update(ctx, dirty) {
			if ((!current || dirty & /*profile*/ 4) && t3_value !== (t3_value = /*profile*/ ctx[2][/*field*/ ctx[10].key] + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, t3_value);
		},
		i: function intro(local) {
			if (current) return;

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (p_outro) p_outro.end(1);

				if (!p_intro) p_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(p, svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"], {
					duration: /*animationDuration*/ ctx[3],
					[/*animationDimension*/ ctx[4]]: -20
				});

				p_intro.start();
			});

			current = true;
		},
		o: function outro(local) {
			if (p_intro) p_intro.invalidate();

			p_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(p, svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"], {
				duration: /*animationDuration*/ ctx[3],
				[/*animationDimension*/ ctx[4]]: 20
			});

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(p);
			if (detaching && p_outro) p_outro.end();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(81:4) {#if !swapping}",
		ctx
	});

	return block;
}

// (80:2) {#each fields as field (field.name)}
function create_each_block(key_1, ctx) {
	let first;
	let if_block_anchor;
	let current;
	let if_block = !/*swapping*/ ctx[1] && create_if_block(ctx);

	const block = {
		key: key_1,
		first: null,
		c: function create() {
			first = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block) if_block.c();
			if_block_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			this.h();
		},
		l: function claim(nodes) {
			first = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block) if_block.l(nodes);
			if_block_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			this.h();
		},
		h: function hydrate() {
			this.first = first;
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, first, anchor);
			if (if_block) if_block.m(target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, if_block_anchor, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			if (!/*swapping*/ ctx[1]) {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*swapping*/ 2) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					}
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			} else if (if_block) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block, 1, 1, () => {
					if_block = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(first);
			if (if_block) if_block.d(detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(if_block_anchor);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(80:2) {#each fields as field (field.name)}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let div;
	let t;
	let each_blocks = [];
	let each_1_lookup = new Map();
	let div_class_value;
	let current;
	let if_block = !/*swapping*/ ctx[1] && create_if_block_1(ctx);
	let each_value = /*fields*/ ctx[5];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	const get_key = ctx => /*field*/ ctx[10].name;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_keys"])(ctx, each_value, get_each_context, get_key);

	for (let i = 0; i < each_value.length; i += 1) {
		let child_ctx = get_each_context(ctx, each_value, i);
		let key = get_key(child_ctx);
		each_1_lookup.set(key, each_blocks[i] = create_each_block(key, child_ctx));
	}

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (if_block) if_block.c();
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { style: true, class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			if (if_block) if_block.l(div_nodes);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div_nodes);
			}

			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "style", /*style*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", div_class_value = "border-2 border-tan " + (/*$$props*/ ctx[6].class || "") + " p-12 items-start");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 70, 0, 1545);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			if (if_block) if_block.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div, null);
			}

			current = true;
		},
		p: function update(ctx, [dirty]) {
			if (!/*swapping*/ ctx[1]) {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*swapping*/ 2) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					}
				} else {
					if_block = create_if_block_1(ctx);
					if_block.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					if_block.m(div, t);
				}
			} else if (if_block) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block, 1, 1, () => {
					if_block = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			if (dirty & /*profile, fields, swapping*/ 38) {
				const each_value = /*fields*/ ctx[5];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_keys"])(ctx, each_value, get_each_context, get_key);
				each_blocks = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_keyed_each"])(each_blocks, dirty, get_key, 1, ctx, each_value, each_1_lookup, div, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["outro_and_destroy_block"], create_each_block, null, get_each_context);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			if (!current || dirty & /*style*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "style", /*style*/ ctx[0]);
			}

			if (!current || dirty & /*$$props*/ 64 && div_class_value !== (div_class_value = "border-2 border-tan " + (/*$$props*/ ctx[6].class || "") + " p-12 items-start")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", div_class_value);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			if (if_block) if_block.d();

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].d();
			}
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { style = "" } = $$props;

	const profiles = [
		{
			name: "Breonna Taylor",
			date: "03/12/2019",
			mannerOfDeath: "Shot",
			armed: "Unarmed",
			age: 26,
			sex: "Female",
			location: "Louisville, KY",
			fleeing: "Not fleeing",
			bodyCamera: "No body camera"
		},
		{
			name: "Chris E.",
			date: "03/16/2020",
			mannerOfDeath: "Shot",
			armed: "Unarmed",
			age: 45,
			sex: "Male",
			location: "Detroit, MI",
			fleeing: "Not fleeing",
			bodyCamera: "No body camera"
		}
	];

	let currentProfile = 0;
	let swapping = false;
	let swapInterval;
	let animationDuration = 200;
	let animationDimension = "y";

	Object(svelte__WEBPACK_IMPORTED_MODULE_2__["onMount"])(() => {
		swapInterval = setInterval(
			async () => {
				$$invalidate(1, swapping = true);
				await Object(utils_time__WEBPACK_IMPORTED_MODULE_3__["delay"])(animationDuration - 5);
				$$invalidate(7, currentProfile = (currentProfile + 1) % profiles.length);
				$$invalidate(1, swapping = false);
			},
			3000
		);
	});

	Object(svelte__WEBPACK_IMPORTED_MODULE_2__["onDestroy"])(() => {
		clearInterval(swapInterval);
	});

	const fields = [
		{ name: "Date", key: "date" },
		{
			name: "Manner of Death",
			key: "mannerOfDeath"
		},
		{ name: "Armed", key: "armed" },
		{ name: "Age", key: "age" },
		{ name: "Sex", key: "sex" },
		{ name: "Location", key: "location" },
		{
			name: "Fleeing the Scene",
			key: "fleeing"
		},
		{ name: "Body Camera", key: "bodyCamera" }
	];

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("StoryCard", $$slots, []);

	$$self.$set = $$new_props => {
		$$invalidate(6, $$props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, $$props), Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["exclude_internal_props"])($$new_props)));
		if ("style" in $$new_props) $$invalidate(0, style = $$new_props.style);
	};

	$$self.$capture_state = () => ({
		fade: svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fade"],
		fly: svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"],
		onDestroy: svelte__WEBPACK_IMPORTED_MODULE_2__["onDestroy"],
		onMount: svelte__WEBPACK_IMPORTED_MODULE_2__["onMount"],
		delay: utils_time__WEBPACK_IMPORTED_MODULE_3__["delay"],
		style,
		profiles,
		currentProfile,
		swapping,
		swapInterval,
		animationDuration,
		animationDimension,
		fields,
		profile
	});

	$$self.$inject_state = $$new_props => {
		$$invalidate(6, $$props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, $$props), $$new_props));
		if ("style" in $$props) $$invalidate(0, style = $$new_props.style);
		if ("currentProfile" in $$props) $$invalidate(7, currentProfile = $$new_props.currentProfile);
		if ("swapping" in $$props) $$invalidate(1, swapping = $$new_props.swapping);
		if ("swapInterval" in $$props) swapInterval = $$new_props.swapInterval;
		if ("animationDuration" in $$props) $$invalidate(3, animationDuration = $$new_props.animationDuration);
		if ("animationDimension" in $$props) $$invalidate(4, animationDimension = $$new_props.animationDimension);
		if ("profile" in $$props) $$invalidate(2, profile = $$new_props.profile);
	};

	let profile;

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*currentProfile*/ 128) {
			$: $$invalidate(2, profile = profiles[currentProfile]);
		}
	};

	$$props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["exclude_internal_props"])($$props);

	return [
		style,
		swapping,
		profile,
		animationDuration,
		animationDimension,
		fields,
		$$props
	];
}

class StoryCard extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { style: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "StoryCard",
			options,
			id: create_fragment.name
		});
	}

	get style() {
		throw new Error("<StoryCard>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set style(value) {
		throw new Error("<StoryCard>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (StoryCard
  = module && module.hot
    ? _Users_samueldesota_d_fightforblacklives_fightforblacklives_com_node_modules_svelte_loader_hot_lib_svelte3_hot_api_js__WEBPACK_IMPORTED_MODULE_4__["applyHmr"]({
        m: module,
        id: "\"src/components/StoryCard.svelte\"",
        hotOptions: {"noPreserveState":false,"noPreserveStateKey":"@!hmr","noReload":false,"optimistic":true,"acceptNamedExports":true,"acceptAccessors":true},
        Component: StoryCard,
        ProxyAdapter: _Users_samueldesota_d_fightforblacklives_fightforblacklives_com_node_modules_svelte_hmr_runtime_proxy_adapter_dom_js__WEBPACK_IMPORTED_MODULE_5__["default"],
        compileData: {"vars":[{"name":"fade","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":false},{"name":"fly","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":false,"referenced_from_script":false},{"name":"onDestroy","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":true},{"name":"onMount","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":true},{"name":"delay","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":true},{"name":"style","export_name":"style","injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":true,"referenced_from_script":false},{"name":"profiles","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":true},{"name":"currentProfile","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":true,"referenced":false,"writable":true,"referenced_from_script":true},{"name":"swapping","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":true,"referenced":true,"writable":true,"referenced_from_script":true},{"name":"swapInterval","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":true,"referenced":false,"writable":true,"referenced_from_script":true},{"name":"animationDuration","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":true,"referenced_from_script":true},{"name":"animationDimension","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":true,"referenced_from_script":false},{"name":"fields","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":false,"referenced_from_script":false},{"name":"profile","export_name":null,"injected":true,"module":false,"mutated":false,"reassigned":true,"referenced":true,"writable":true,"referenced_from_script":false},{"name":"$props","export_name":null,"injected":true,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":false,"referenced_from_script":false}],"accessors":false},
        compileOptions: {"filename":"/Users/samueldesota/d/fightforblacklives/fightforblacklives.com/src/components/StoryCard.svelte","format":"esm","dev":true,"hydratable":true},
      })
    : StoryCard);

/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../node_modules/webpack/buildin/harmony-module.js */ "./node_modules/webpack/buildin/harmony-module.js")(module)))

/***/ }),

/***/ "./src/components/StoryCard2.svelte":
/*!******************************************!*\
  !*** ./src/components/StoryCard2.svelte ***!
  \******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* WEBPACK VAR INJECTION */(function(module) {/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte_transition__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte/transition */ "./node_modules/svelte/transition/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var utils_time__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! utils/time */ "./src/utils/time.ts");
/* harmony import */ var utils_time__WEBPACK_IMPORTED_MODULE_3___default = /*#__PURE__*/__webpack_require__.n(utils_time__WEBPACK_IMPORTED_MODULE_3__);
/* harmony import */ var _Users_samueldesota_d_fightforblacklives_fightforblacklives_com_node_modules_svelte_loader_hot_lib_svelte3_hot_api_js__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./node_modules/svelte-loader-hot/lib/svelte3/hot-api.js */ "./node_modules/svelte-loader-hot/lib/svelte3/hot-api.js");
/* harmony import */ var _Users_samueldesota_d_fightforblacklives_fightforblacklives_com_node_modules_svelte_hmr_runtime_proxy_adapter_dom_js__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ./node_modules/svelte-hmr/runtime/proxy-adapter-dom.js */ "./node_modules/svelte-hmr/runtime/proxy-adapter-dom.js");
/* src/components/StoryCard2.svelte generated by Svelte v3.23.0 */





const file = "src/components/StoryCard2.svelte";

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[13] = list[i];
	return child_ctx;
}

// (91:4) {#if swapping !== 'name'}
function create_if_block_1(ctx) {
	let span;
	let t_value = /*getField*/ ctx[7](/*swapped*/ ctx[1], /*swapping*/ ctx[2], /*profile*/ ctx[3], /*nextProfile*/ ctx[4], "name") + "";
	let t;
	let span_intro;
	let span_outro;
	let current;

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "inline-block");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 91, 6, 2234);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t);
			current = true;
		},
		p: function update(ctx, dirty) {
			if ((!current || dirty & /*swapped, swapping, profile, nextProfile*/ 30) && t_value !== (t_value = /*getField*/ ctx[7](/*swapped*/ ctx[1], /*swapping*/ ctx[2], /*profile*/ ctx[3], /*nextProfile*/ ctx[4], "name") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		i: function intro(local) {
			if (current) return;

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (span_outro) span_outro.end(1);

				if (!span_intro) span_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span, svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"], {
					duration: /*animationDuration*/ ctx[5],
					[/*animationDimension*/ ctx[6]]: 20
				});

				span_intro.start();
			});

			current = true;
		},
		o: function outro(local) {
			if (span_intro) span_intro.invalidate();

			span_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(span, svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"], {
				duration: /*animationDuration*/ ctx[5],
				[/*animationDimension*/ ctx[6]]: -20
			});

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching && span_outro) span_outro.end();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(91:4) {#if swapping !== 'name'}",
		ctx
	});

	return block;
}

// (104:6) {#if swapping !== field.key}
function create_if_block(ctx) {
	let span;
	let t_value = /*getField*/ ctx[7](/*swapped*/ ctx[1], /*swapping*/ ctx[2], /*profile*/ ctx[3], /*nextProfile*/ ctx[4], /*field*/ ctx[13].key) + "";
	let t;
	let span_intro;
	let span_outro;
	let current;

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "text-brown-gray inline-block");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 104, 8, 2681);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t);
			current = true;
		},
		p: function update(ctx, dirty) {
			if ((!current || dirty & /*swapped, swapping, profile, nextProfile*/ 30) && t_value !== (t_value = /*getField*/ ctx[7](/*swapped*/ ctx[1], /*swapping*/ ctx[2], /*profile*/ ctx[3], /*nextProfile*/ ctx[4], /*field*/ ctx[13].key) + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		i: function intro(local) {
			if (current) return;

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_render_callback"])(() => {
				if (span_outro) span_outro.end(1);

				if (!span_intro) span_intro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_in_transition"])(span, svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"], {
					duration: /*animationDuration*/ ctx[5],
					[/*animationDimension*/ ctx[6]]: 15
				});

				span_intro.start();
			});

			current = true;
		},
		o: function outro(local) {
			if (span_intro) span_intro.invalidate();

			span_outro = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_out_transition"])(span, svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"], {
				duration: /*animationDuration*/ ctx[5],
				[/*animationDimension*/ ctx[6]]: -15
			});

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			if (detaching && span_outro) span_outro.end();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(104:6) {#if swapping !== field.key}",
		ctx
	});

	return block;
}

// (100:2) {#each fields as field (field.name)}
function create_each_block(key_1, ctx) {
	let p;
	let span;
	let t0_value = /*field*/ ctx[13].name + "";
	let t0;
	let t1;
	let t2;
	let t3;
	let current;
	let if_block = /*swapping*/ ctx[2] !== /*field*/ ctx[13].key && create_if_block(ctx);

	const block = {
		key: key_1,
		first: null,
		c: function create() {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block) if_block.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h();
		},
		l: function claim(nodes) {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true });
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, ":");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(p_nodes);
			if (if_block) if_block.l(p_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(p_nodes);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "mr-2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 101, 6, 2597);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p, "class", "text-2xl mt-4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 100, 4, 2565);
			this.first = p;
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, p, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t2);
			if (if_block) if_block.m(p, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t3);
			current = true;
		},
		p: function update(ctx, dirty) {
			if (/*swapping*/ ctx[2] !== /*field*/ ctx[13].key) {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*swapping*/ 4) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					}
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					if_block.m(p, t3);
				}
			} else if (if_block) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block, 1, 1, () => {
					if_block = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(p);
			if (if_block) if_block.d();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(100:2) {#each fields as field (field.name)}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let div;
	let h2;
	let t;
	let each_blocks = [];
	let each_1_lookup = new Map();
	let div_class_value;
	let current;
	let if_block = /*swapping*/ ctx[2] !== "name" && create_if_block_1(ctx);
	let each_value = /*fields*/ ctx[8];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	const get_key = ctx => /*field*/ ctx[13].name;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_keys"])(ctx, each_value, get_each_context, get_key);

	for (let i = 0; i < each_value.length; i += 1) {
		let child_ctx = get_each_context(ctx, each_value, i);
		let key = get_key(child_ctx);
		each_1_lookup.set(key, each_blocks[i] = create_each_block(key, child_ctx));
	}

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			if (if_block) if_block.c();
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { style: true, class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "H2", { style: true, class: true });
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			if (if_block) if_block.l(h2_nodes);
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div_nodes);
			}

			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(h2, "height", "1.4em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "text-4xl font-bold");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 89, 2, 2144);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "style", /*style*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", div_class_value = "border-2 border-tan " + (/*$$props*/ ctx[9].class || "") + " p-12 items-start");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 88, 0, 2061);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, h2);
			if (if_block) if_block.m(h2, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div, null);
			}

			current = true;
		},
		p: function update(ctx, [dirty]) {
			if (/*swapping*/ ctx[2] !== "name") {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*swapping*/ 4) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					}
				} else {
					if_block = create_if_block_1(ctx);
					if_block.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					if_block.m(h2, null);
				}
			} else if (if_block) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block, 1, 1, () => {
					if_block = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			if (dirty & /*getField, swapped, swapping, profile, nextProfile, fields*/ 414) {
				const each_value = /*fields*/ ctx[8];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_keys"])(ctx, each_value, get_each_context, get_key);
				each_blocks = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_keyed_each"])(each_blocks, dirty, get_key, 1, ctx, each_value, each_1_lookup, div, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["outro_and_destroy_block"], create_each_block, null, get_each_context);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			if (!current || dirty & /*style*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "style", /*style*/ ctx[0]);
			}

			if (!current || dirty & /*$$props*/ 512 && div_class_value !== (div_class_value = "border-2 border-tan " + (/*$$props*/ ctx[9].class || "") + " p-12 items-start")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", div_class_value);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			if (if_block) if_block.d();

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].d();
			}
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { style = "" } = $$props;

	const profiles = [
		{
			name: "Breonna Taylor",
			date: "03/12/2019",
			mannerOfDeath: "Shot",
			armed: "Unarmed",
			age: 26,
			sex: "Female",
			location: "Louisville, KY",
			fleeing: "Not fleeing",
			bodyCamera: "No body camera"
		},
		{
			name: "Chris E.",
			date: "03/16/2020",
			mannerOfDeath: "Shot",
			armed: "Unarmed",
			age: 45,
			sex: "Male",
			location: "Detroit, MI",
			fleeing: "Not fleeing",
			bodyCamera: "No body camera"
		}
	];

	let currentProfile = 0;
	let swapped = new Set();
	let swapping = false;
	let swapInterval;
	let animationDuration = 100;
	let animationDimension = "y";

	Object(svelte__WEBPACK_IMPORTED_MODULE_2__["onMount"])(() => {
		swapInterval = setInterval(
			async () => {
				$$invalidate(1, swapped = new Set());
				const nextProfile = (currentProfile + 1) % profiles.length;
				$$invalidate(2, swapping = "name");
				await Object(utils_time__WEBPACK_IMPORTED_MODULE_3__["delay"])(animationDuration);
				swapped.add("name");

				for (const field of fields) {
					$$invalidate(2, swapping = field.key);
					await Object(utils_time__WEBPACK_IMPORTED_MODULE_3__["delay"])(animationDuration * 0.9);
					swapped.add(field.key);
				}

				$$invalidate(10, currentProfile = nextProfile);
				$$invalidate(2, swapping = false);
			},
			4500
		);
	});

	Object(svelte__WEBPACK_IMPORTED_MODULE_2__["onDestroy"])(() => {
		clearInterval(swapInterval);
	});

	const getField = (swapped, swapping, profile, nextProfile, key) => {
		return swapping === false || !swapped.has(key)
		? profile[key]
		: nextProfile[key];
	};

	const fields = [
		{ name: "Date", key: "date" },
		{
			name: "Manner of Death",
			key: "mannerOfDeath"
		},
		{ name: "Armed", key: "armed" },
		{ name: "Age", key: "age" },
		{ name: "Sex", key: "sex" },
		{ name: "Location", key: "location" },
		{
			name: "Fleeing the Scene",
			key: "fleeing"
		},
		{ name: "Body Camera", key: "bodyCamera" }
	];

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("StoryCard2", $$slots, []);

	$$self.$set = $$new_props => {
		$$invalidate(9, $$props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, $$props), Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["exclude_internal_props"])($$new_props)));
		if ("style" in $$new_props) $$invalidate(0, style = $$new_props.style);
	};

	$$self.$capture_state = () => ({
		fade: svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fade"],
		fly: svelte_transition__WEBPACK_IMPORTED_MODULE_1__["fly"],
		onDestroy: svelte__WEBPACK_IMPORTED_MODULE_2__["onDestroy"],
		onMount: svelte__WEBPACK_IMPORTED_MODULE_2__["onMount"],
		delay: utils_time__WEBPACK_IMPORTED_MODULE_3__["delay"],
		style,
		profiles,
		currentProfile,
		swapped,
		swapping,
		swapInterval,
		animationDuration,
		animationDimension,
		getField,
		fields,
		profile,
		nextProfile
	});

	$$self.$inject_state = $$new_props => {
		$$invalidate(9, $$props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, $$props), $$new_props));
		if ("style" in $$props) $$invalidate(0, style = $$new_props.style);
		if ("currentProfile" in $$props) $$invalidate(10, currentProfile = $$new_props.currentProfile);
		if ("swapped" in $$props) $$invalidate(1, swapped = $$new_props.swapped);
		if ("swapping" in $$props) $$invalidate(2, swapping = $$new_props.swapping);
		if ("swapInterval" in $$props) swapInterval = $$new_props.swapInterval;
		if ("animationDuration" in $$props) $$invalidate(5, animationDuration = $$new_props.animationDuration);
		if ("animationDimension" in $$props) $$invalidate(6, animationDimension = $$new_props.animationDimension);
		if ("profile" in $$props) $$invalidate(3, profile = $$new_props.profile);
		if ("nextProfile" in $$props) $$invalidate(4, nextProfile = $$new_props.nextProfile);
	};

	let profile;
	let nextProfile;

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*currentProfile*/ 1024) {
			$: $$invalidate(3, profile = profiles[currentProfile]);
		}

		if ($$self.$$.dirty & /*currentProfile*/ 1024) {
			$: $$invalidate(4, nextProfile = profiles[(currentProfile + 1) % profiles.length]);
		}
	};

	$$props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["exclude_internal_props"])($$props);

	return [
		style,
		swapped,
		swapping,
		profile,
		nextProfile,
		animationDuration,
		animationDimension,
		getField,
		fields,
		$$props
	];
}

class StoryCard2 extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { style: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "StoryCard2",
			options,
			id: create_fragment.name
		});
	}

	get style() {
		throw new Error("<StoryCard2>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set style(value) {
		throw new Error("<StoryCard2>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (StoryCard2
  = module && module.hot
    ? _Users_samueldesota_d_fightforblacklives_fightforblacklives_com_node_modules_svelte_loader_hot_lib_svelte3_hot_api_js__WEBPACK_IMPORTED_MODULE_4__["applyHmr"]({
        m: module,
        id: "\"src/components/StoryCard2.svelte\"",
        hotOptions: {"noPreserveState":false,"noPreserveStateKey":"@!hmr","noReload":false,"optimistic":true,"acceptNamedExports":true,"acceptAccessors":true},
        Component: StoryCard2,
        ProxyAdapter: _Users_samueldesota_d_fightforblacklives_fightforblacklives_com_node_modules_svelte_hmr_runtime_proxy_adapter_dom_js__WEBPACK_IMPORTED_MODULE_5__["default"],
        compileData: {"vars":[{"name":"fade","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":false},{"name":"fly","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":false,"referenced_from_script":false},{"name":"onDestroy","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":true},{"name":"onMount","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":true},{"name":"delay","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":true},{"name":"style","export_name":"style","injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":true,"referenced_from_script":false},{"name":"profiles","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":false,"writable":false,"referenced_from_script":true},{"name":"currentProfile","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":true,"referenced":false,"writable":true,"referenced_from_script":true},{"name":"swapped","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":true,"referenced":true,"writable":true,"referenced_from_script":true},{"name":"swapping","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":true,"referenced":true,"writable":true,"referenced_from_script":true},{"name":"swapInterval","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":true,"referenced":false,"writable":true,"referenced_from_script":true},{"name":"animationDuration","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":true,"referenced_from_script":true},{"name":"animationDimension","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":true,"referenced_from_script":false},{"name":"getField","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":false,"referenced_from_script":false},{"name":"fields","export_name":null,"injected":false,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":false,"referenced_from_script":true},{"name":"profile","export_name":null,"injected":true,"module":false,"mutated":false,"reassigned":true,"referenced":true,"writable":true,"referenced_from_script":false},{"name":"nextProfile","export_name":null,"injected":true,"module":false,"mutated":false,"reassigned":true,"referenced":true,"writable":true,"referenced_from_script":false},{"name":"$props","export_name":null,"injected":true,"module":false,"mutated":false,"reassigned":false,"referenced":true,"writable":false,"referenced_from_script":false}],"accessors":false},
        compileOptions: {"filename":"/Users/samueldesota/d/fightforblacklives/fightforblacklives.com/src/components/StoryCard2.svelte","format":"esm","dev":true,"hydratable":true},
      })
    : StoryCard2);

/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../node_modules/webpack/buildin/harmony-module.js */ "./node_modules/webpack/buildin/harmony-module.js")(module)))

/***/ }),

/***/ "./src/utils/time.ts":
/*!***************************!*\
  !*** ./src/utils/time.ts ***!
  \***************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

exports.__esModule = true;
exports.delay = void 0;
exports.delay = function (amount) {
    return new Promise(function (resolve) {
        return setTimeout(resolve, amount);
    });
};


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9TdG9yeUNhcmQuc3ZlbHRlIiwid2VicGFjazovLy8uL3NyYy9jb21wb25lbnRzL1N0b3J5Q2FyZDIuc3ZlbHRlIiwid2VicGFjazovLy8uL3NyYy91dGlscy90aW1lLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUNnRDtBQUNGO0FBQ1Q7Ozs7Ozs7Ozs7OzsyQkF5RTlCLEdBQU8sSUFBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztpRkFBWixHQUFPLElBQUMsSUFBSTs7Ozs7Ozs7O0tBSEgsUUFBUSx3QkFBRSxHQUFpQjs2QkFBRyxHQUFrQixPQUFJLEVBQUU7Ozs7Ozs7Ozs7OztJQUNyRCxRQUFRLHdCQUFFLEdBQWlCOzRCQUFHLEdBQWtCLE1BQUcsRUFBRTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MEJBVzFDLEdBQUssS0FBQyxJQUFJOzs7Ozs0QkFDYyxHQUFPLGNBQUMsR0FBSyxLQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21GQUFqQixHQUFPLGNBQUMsR0FBSyxLQUFDLEdBQUc7Ozs7Ozs7OztLQUhuRCxRQUFRLHdCQUFFLEdBQWlCOzZCQUFHLEdBQWtCLE9BQUksRUFBRTs7Ozs7Ozs7Ozs7O0lBQ3JELFFBQVEsd0JBQUUsR0FBaUI7NEJBQUcsR0FBa0IsTUFBRyxFQUFFOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OEJBSjlELEdBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxQkFBUixHQUFROzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OEJBVFYsR0FBUTs2QkFRUCxHQUFNOztrQ0FBVyxHQUFLLEtBQUMsSUFBSTs7O2dDQUFoQyxNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MElBVGlDLEdBQU8sSUFBQyxLQUFLLElBQUksRUFBRTs7Ozs7Ozs7Ozs7Ozs7O3FCQUNwRCxHQUFROzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7a0NBUVAsR0FBTTs7Ozs7Ozs7Ozs7OzBIQVQwQixHQUFPLElBQUMsS0FBSyxJQUFJLEVBQUU7Ozs7Ozs7O2tDQVN4RCxNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BMUVLLEtBQUssR0FBRyxFQUFFOztPQUVmLFFBQVE7O0dBRVYsSUFBSSxFQUFFLGdCQUFnQjtHQUN0QixJQUFJLEVBQUUsWUFBWTtHQUNsQixhQUFhLEVBQUUsTUFBTTtHQUNyQixLQUFLLEVBQUUsU0FBUztHQUNoQixHQUFHLEVBQUUsRUFBRTtHQUNQLEdBQUcsRUFBRSxRQUFRO0dBQ2IsUUFBUSxFQUFFLGdCQUFnQjtHQUMxQixPQUFPLEVBQUUsYUFBYTtHQUN0QixVQUFVLEVBQUUsZ0JBQWdCOzs7R0FJNUIsSUFBSSxFQUFFLFVBQVU7R0FDaEIsSUFBSSxFQUFFLFlBQVk7R0FDbEIsYUFBYSxFQUFFLE1BQU07R0FDckIsS0FBSyxFQUFFLFNBQVM7R0FDaEIsR0FBRyxFQUFFLEVBQUU7R0FDUCxHQUFHLEVBQUUsTUFBTTtHQUNYLFFBQVEsRUFBRSxhQUFhO0dBQ3ZCLE9BQU8sRUFBRSxhQUFhO0dBQ3RCLFVBQVUsRUFBRSxnQkFBZ0I7Ozs7S0FJNUIsY0FBYyxHQUFHLENBQUM7S0FFbEIsUUFBUSxHQUFHLEtBQUs7S0FDaEIsWUFBWTtLQUVaLGlCQUFpQixHQUFHLEdBQUc7S0FDdkIsa0JBQWtCLEdBQUcsR0FBRzs7Q0FFNUIsc0RBQU87RUFDTCxZQUFZLEdBQUcsV0FBVzs7b0JBQ3hCLFFBQVEsR0FBRyxJQUFJO1VBRVQsd0RBQUssQ0FBQyxpQkFBaUIsR0FBRyxDQUFDO29CQUVqQyxjQUFjLElBQUksY0FBYyxHQUFHLENBQUMsSUFBSSxRQUFRLENBQUMsTUFBTTtvQkFDdkQsUUFBUSxHQUFHLEtBQUs7O0dBQ2YsSUFBSTs7OztDQUdULHdEQUFTO0VBQ1AsYUFBYSxDQUFDLFlBQVk7OztPQUt0QixNQUFNO0lBQ1IsSUFBSSxFQUFFLE1BQU0sRUFBRSxHQUFHLEVBQUUsTUFBTTs7R0FDekIsSUFBSSxFQUFFLGlCQUFpQjtHQUFFLEdBQUcsRUFBRSxlQUFlOztJQUM3QyxJQUFJLEVBQUUsT0FBTyxFQUFFLEdBQUcsRUFBRSxPQUFPO0lBQzNCLElBQUksRUFBRSxLQUFLLEVBQUUsR0FBRyxFQUFFLEtBQUs7SUFDdkIsSUFBSSxFQUFFLEtBQUssRUFBRSxHQUFHLEVBQUUsS0FBSztJQUN2QixJQUFJLEVBQUUsVUFBVSxFQUFFLEdBQUcsRUFBRSxVQUFVOztHQUNqQyxJQUFJLEVBQUUsbUJBQW1CO0dBQUUsR0FBRyxFQUFFLFNBQVM7O0lBQ3pDLElBQUksRUFBRSxhQUFhLEVBQUUsR0FBRyxFQUFFLFlBQVk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0dBVjFDLENBQUMsa0JBQUUsT0FBTyxHQUFHLFFBQVEsQ0FBQyxjQUFjOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUN2RFU7QUFDRjtBQUNUOzs7Ozs7Ozs7Ozs7NEJBNEY1QixHQUFRLGdCQUFDLEdBQU8sa0JBQUUsR0FBUSxpQkFBRSxHQUFPLHFCQUFFLEdBQVcsS0FBRSxNQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttSEFBeEQsR0FBUSxnQkFBQyxHQUFPLGtCQUFFLEdBQVEsaUJBQUUsR0FBTyxxQkFBRSxHQUFXLEtBQUUsTUFBTTs7Ozs7Ozs7O0tBRi9DLFFBQVEsd0JBQUUsR0FBaUI7NkJBQUcsR0FBa0IsTUFBRyxFQUFFOzs7Ozs7Ozs7Ozs7SUFDcEQsUUFBUSx3QkFBRSxHQUFpQjs0QkFBRyxHQUFrQixPQUFJLEVBQUU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NEJBYzlELEdBQVEsZ0JBQUMsR0FBTyxrQkFBRSxHQUFRLGlCQUFFLEdBQU8scUJBQUUsR0FBVyxlQUFFLEdBQUssS0FBQyxHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttSEFBM0QsR0FBUSxnQkFBQyxHQUFPLGtCQUFFLEdBQVEsaUJBQUUsR0FBTyxxQkFBRSxHQUFXLGVBQUUsR0FBSyxLQUFDLEdBQUc7Ozs7Ozs7OztLQUhsRCxRQUFRLHdCQUFFLEdBQWlCOzZCQUFHLEdBQWtCLE1BQUcsRUFBRTs7Ozs7Ozs7Ozs7O0lBQ3BELFFBQVEsd0JBQUUsR0FBaUI7NEJBQUcsR0FBa0IsT0FBSSxFQUFFOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzswQkFMakQsR0FBSyxLQUFDLElBQUk7Ozs7Ozs2QkFFekIsR0FBUSxrQkFBSyxHQUFLLEtBQUMsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JBQXRCLEdBQVEsa0JBQUssR0FBSyxLQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2QkFieEIsR0FBUSxRQUFLLE1BQU07NkJBU25CLEdBQU07O2tDQUFXLEdBQUssS0FBQyxJQUFJOzs7Z0NBQWhDLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MElBWGlDLEdBQU8sSUFBQyxLQUFLLElBQUksRUFBRTs7Ozs7Ozs7Ozs7Ozs7OztvQkFFbkQsR0FBUSxRQUFLLE1BQU07Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztrQ0FTbkIsR0FBTTs7Ozs7Ozs7Ozs7OzJIQVgwQixHQUFPLElBQUMsS0FBSyxJQUFJLEVBQUU7Ozs7Ozs7O2tDQVd4RCxNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BOUZLLEtBQUssR0FBRyxFQUFFOztPQUVmLFFBQVE7O0dBRVYsSUFBSSxFQUFFLGdCQUFnQjtHQUN0QixJQUFJLEVBQUUsWUFBWTtHQUNsQixhQUFhLEVBQUUsTUFBTTtHQUNyQixLQUFLLEVBQUUsU0FBUztHQUNoQixHQUFHLEVBQUUsRUFBRTtHQUNQLEdBQUcsRUFBRSxRQUFRO0dBQ2IsUUFBUSxFQUFFLGdCQUFnQjtHQUMxQixPQUFPLEVBQUUsYUFBYTtHQUN0QixVQUFVLEVBQUUsZ0JBQWdCOzs7R0FJNUIsSUFBSSxFQUFFLFVBQVU7R0FDaEIsSUFBSSxFQUFFLFlBQVk7R0FDbEIsYUFBYSxFQUFFLE1BQU07R0FDckIsS0FBSyxFQUFFLFNBQVM7R0FDaEIsR0FBRyxFQUFFLEVBQUU7R0FDUCxHQUFHLEVBQUUsTUFBTTtHQUNYLFFBQVEsRUFBRSxhQUFhO0dBQ3ZCLE9BQU8sRUFBRSxhQUFhO0dBQ3RCLFVBQVUsRUFBRSxnQkFBZ0I7Ozs7S0FJNUIsY0FBYyxHQUFHLENBQUM7S0FFbEIsT0FBTyxPQUFPLEdBQUc7S0FDakIsUUFBUSxHQUFHLEtBQUs7S0FDaEIsWUFBWTtLQUVaLGlCQUFpQixHQUFHLEdBQUc7S0FDdkIsa0JBQWtCLEdBQUcsR0FBRzs7Q0FFNUIsc0RBQU87RUFDTCxZQUFZLEdBQUcsV0FBVzs7b0JBQ3hCLE9BQU8sT0FBTyxHQUFHO1VBRVgsV0FBVyxJQUFJLGNBQWMsR0FBRyxDQUFDLElBQUksUUFBUSxDQUFDLE1BQU07b0JBRTFELFFBQVEsR0FBRyxNQUFNO1VBQ1gsd0RBQUssQ0FBQyxpQkFBaUI7SUFDN0IsT0FBTyxDQUFDLEdBQUcsQ0FBQyxNQUFNOztlQUVQLEtBQUssSUFBSSxNQUFNO3FCQUN4QixRQUFRLEdBQUcsS0FBSyxDQUFDLEdBQUc7V0FDZCx3REFBSyxDQUFDLGlCQUFpQixHQUFHLEdBQUc7S0FDbkMsT0FBTyxDQUFDLEdBQUcsQ0FBQyxLQUFLLENBQUMsR0FBRzs7O3FCQUd2QixjQUFjLEdBQUcsV0FBVztvQkFDNUIsUUFBUSxHQUFHLEtBQUs7O0dBQ2YsSUFBSTs7OztDQUdULHdEQUFTO0VBQ1AsYUFBYSxDQUFDLFlBQVk7OztPQU10QixRQUFRLElBQUksT0FBTyxFQUFFLFFBQVEsRUFBRSxPQUFPLEVBQUUsV0FBVyxFQUFFLEdBQUc7U0FDckQsUUFBUSxLQUFLLEtBQUssS0FBSyxPQUFPLENBQUMsR0FBRyxDQUFDLEdBQUc7SUFDekMsT0FBTyxDQUFDLEdBQUc7SUFDWCxXQUFXLENBQUMsR0FBRzs7O09BR2YsTUFBTTtJQUNSLElBQUksRUFBRSxNQUFNLEVBQUUsR0FBRyxFQUFFLE1BQU07O0dBQ3pCLElBQUksRUFBRSxpQkFBaUI7R0FBRSxHQUFHLEVBQUUsZUFBZTs7SUFDN0MsSUFBSSxFQUFFLE9BQU8sRUFBRSxHQUFHLEVBQUUsT0FBTztJQUMzQixJQUFJLEVBQUUsS0FBSyxFQUFFLEdBQUcsRUFBRSxLQUFLO0lBQ3ZCLElBQUksRUFBRSxLQUFLLEVBQUUsR0FBRyxFQUFFLEtBQUs7SUFDdkIsSUFBSSxFQUFFLFVBQVUsRUFBRSxHQUFHLEVBQUUsVUFBVTs7R0FDakMsSUFBSSxFQUFFLG1CQUFtQjtHQUFFLEdBQUcsRUFBRSxTQUFTOztJQUN6QyxJQUFJLEVBQUUsYUFBYSxFQUFFLEdBQUcsRUFBRSxZQUFZOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztHQWpCMUMsQ0FBQyxrQkFBRSxPQUFPLEdBQUcsUUFBUSxDQUFDLGNBQWM7Ozs7R0FDcEMsQ0FBQyxrQkFBRSxXQUFXLEdBQUcsUUFBUSxFQUFFLGNBQWMsR0FBRyxDQUFDLElBQUksUUFBUSxDQUFDLE1BQU07Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNwRXJELGFBQUssR0FBRyxVQUFDLE1BQWM7SUFDbEMsT0FBTyxJQUFJLE9BQU8sQ0FBQyxVQUFDLE9BQU87UUFDekIsT0FBTyxVQUFVLENBQUMsT0FBTyxFQUFFLE1BQU0sQ0FBQyxDQUFDO0lBQ3JDLENBQUMsQ0FBQyxDQUFDO0FBQ0wsQ0FBQyxDQUFDIiwiZmlsZSI6ImJkYjY0YTljNTQyYzdhYzQ3NGRkL2luZGV4fnNjcmF0Y2guaW5kZXh+c2NyYXRjaC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGltcG9ydCB7IGZhZGUsIGZseSB9IGZyb20gXCJzdmVsdGUvdHJhbnNpdGlvblwiO1xuICBpbXBvcnQgeyBvbkRlc3Ryb3ksIG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCI7XG4gIGltcG9ydCB7IGRlbGF5IH0gZnJvbSBcInV0aWxzL3RpbWVcIjtcblxuICBleHBvcnQgbGV0IHN0eWxlID0gXCJcIjtcblxuICBjb25zdCBwcm9maWxlcyA9IFtcbiAgICB7XG4gICAgICBuYW1lOiBcIkJyZW9ubmEgVGF5bG9yXCIsXG4gICAgICBkYXRlOiBcIjAzLzEyLzIwMTlcIixcbiAgICAgIG1hbm5lck9mRGVhdGg6IFwiU2hvdFwiLFxuICAgICAgYXJtZWQ6IFwiVW5hcm1lZFwiLFxuICAgICAgYWdlOiAyNixcbiAgICAgIHNleDogXCJGZW1hbGVcIixcbiAgICAgIGxvY2F0aW9uOiBcIkxvdWlzdmlsbGUsIEtZXCIsXG4gICAgICBmbGVlaW5nOiBcIk5vdCBmbGVlaW5nXCIsXG4gICAgICBib2R5Q2FtZXJhOiBcIk5vIGJvZHkgY2FtZXJhXCJcbiAgICB9LFxuXG4gICAge1xuICAgICAgbmFtZTogXCJDaHJpcyBFLlwiLFxuICAgICAgZGF0ZTogXCIwMy8xNi8yMDIwXCIsXG4gICAgICBtYW5uZXJPZkRlYXRoOiBcIlNob3RcIixcbiAgICAgIGFybWVkOiBcIlVuYXJtZWRcIixcbiAgICAgIGFnZTogNDUsXG4gICAgICBzZXg6IFwiTWFsZVwiLFxuICAgICAgbG9jYXRpb246IFwiRGV0cm9pdCwgTUlcIixcbiAgICAgIGZsZWVpbmc6IFwiTm90IGZsZWVpbmdcIixcbiAgICAgIGJvZHlDYW1lcmE6IFwiTm8gYm9keSBjYW1lcmFcIlxuICAgIH1cbiAgXTtcblxuICBsZXQgY3VycmVudFByb2ZpbGUgPSAwO1xuXG4gIGxldCBzd2FwcGluZyA9IGZhbHNlO1xuICBsZXQgc3dhcEludGVydmFsO1xuXG4gIGxldCBhbmltYXRpb25EdXJhdGlvbiA9IDIwMDtcbiAgbGV0IGFuaW1hdGlvbkRpbWVuc2lvbiA9IFwieVwiO1xuXG4gIG9uTW91bnQoKCkgPT4ge1xuICAgIHN3YXBJbnRlcnZhbCA9IHNldEludGVydmFsKGFzeW5jICgpID0+IHtcbiAgICAgIHN3YXBwaW5nID0gdHJ1ZTtcblxuICAgICAgYXdhaXQgZGVsYXkoYW5pbWF0aW9uRHVyYXRpb24gLSA1KTtcblxuICAgICAgY3VycmVudFByb2ZpbGUgPSAoY3VycmVudFByb2ZpbGUgKyAxKSAlIHByb2ZpbGVzLmxlbmd0aDtcbiAgICAgIHN3YXBwaW5nID0gZmFsc2U7XG4gICAgfSwgMzAwMCk7XG4gIH0pO1xuXG4gIG9uRGVzdHJveSgoKSA9PiB7XG4gICAgY2xlYXJJbnRlcnZhbChzd2FwSW50ZXJ2YWwpO1xuICB9KTtcblxuICAkOiBwcm9maWxlID0gcHJvZmlsZXNbY3VycmVudFByb2ZpbGVdO1xuXG4gIGNvbnN0IGZpZWxkcyA9IFtcbiAgICB7IG5hbWU6IFwiRGF0ZVwiLCBrZXk6IFwiZGF0ZVwiIH0sXG4gICAgeyBuYW1lOiBcIk1hbm5lciBvZiBEZWF0aFwiLCBrZXk6IFwibWFubmVyT2ZEZWF0aFwiIH0sXG4gICAgeyBuYW1lOiBcIkFybWVkXCIsIGtleTogXCJhcm1lZFwiIH0sXG4gICAgeyBuYW1lOiBcIkFnZVwiLCBrZXk6IFwiYWdlXCIgfSxcbiAgICB7IG5hbWU6IFwiU2V4XCIsIGtleTogXCJzZXhcIiB9LFxuICAgIHsgbmFtZTogXCJMb2NhdGlvblwiLCBrZXk6IFwibG9jYXRpb25cIiB9LFxuICAgIHsgbmFtZTogXCJGbGVlaW5nIHRoZSBTY2VuZVwiLCBrZXk6IFwiZmxlZWluZ1wiIH0sXG4gICAgeyBuYW1lOiBcIkJvZHkgQ2FtZXJhXCIsIGtleTogXCJib2R5Q2FtZXJhXCIgfVxuICBdO1xuPC9zY3JpcHQ+XG5cbjxkaXYge3N0eWxlfSBjbGFzcz1cImJvcmRlci0yIGJvcmRlci10YW4geyQkcHJvcHMuY2xhc3MgfHwgJyd9IHAtMTIgaXRlbXMtc3RhcnRcIj5cbiAgeyNpZiAhc3dhcHBpbmd9XG4gICAgPGgyXG4gICAgICBpbjpmbHk9e3sgZHVyYXRpb246IGFuaW1hdGlvbkR1cmF0aW9uLCBbYW5pbWF0aW9uRGltZW5zaW9uXTogLTIwIH19XG4gICAgICBvdXQ6Zmx5PXt7IGR1cmF0aW9uOiBhbmltYXRpb25EdXJhdGlvbiwgW2FuaW1hdGlvbkRpbWVuc2lvbl06IDIwIH19XG4gICAgICBjbGFzcz1cInRleHQtNHhsIGZvbnQtYm9sZFwiPlxuICAgICAge3Byb2ZpbGUubmFtZX1cbiAgICA8L2gyPlxuICB7L2lmfVxuICB7I2VhY2ggZmllbGRzIGFzIGZpZWxkIChmaWVsZC5uYW1lKX1cbiAgICB7I2lmICFzd2FwcGluZ31cbiAgICAgIDxwXG4gICAgICAgIGNsYXNzPVwidGV4dC0yeGwgbXQtNFwiXG4gICAgICAgIGluOmZseT17eyBkdXJhdGlvbjogYW5pbWF0aW9uRHVyYXRpb24sIFthbmltYXRpb25EaW1lbnNpb25dOiAtMjAgfX1cbiAgICAgICAgb3V0OmZseT17eyBkdXJhdGlvbjogYW5pbWF0aW9uRHVyYXRpb24sIFthbmltYXRpb25EaW1lbnNpb25dOiAyMCB9fT5cbiAgICAgICAgPHNwYW4gY2xhc3M9XCJtci00XCI+e2ZpZWxkLm5hbWV9Ojwvc3Bhbj5cbiAgICAgICAgPHNwYW4gY2xhc3M9XCJ0ZXh0LWJyb3duLWdyYXkgaW5saW5lLWJsb2NrXCI+e3Byb2ZpbGVbZmllbGQua2V5XX08L3NwYW4+XG4gICAgICA8L3A+XG4gICAgey9pZn1cbiAgey9lYWNofVxuPC9kaXY+XG4iLCI8c2NyaXB0PlxuICBpbXBvcnQgeyBmYWRlLCBmbHkgfSBmcm9tIFwic3ZlbHRlL3RyYW5zaXRpb25cIjtcbiAgaW1wb3J0IHsgb25EZXN0cm95LCBvbk1vdW50IH0gZnJvbSBcInN2ZWx0ZVwiO1xuICBpbXBvcnQgeyBkZWxheSB9IGZyb20gXCJ1dGlscy90aW1lXCI7XG5cbiAgZXhwb3J0IGxldCBzdHlsZSA9IFwiXCI7XG5cbiAgY29uc3QgcHJvZmlsZXMgPSBbXG4gICAge1xuICAgICAgbmFtZTogXCJCcmVvbm5hIFRheWxvclwiLFxuICAgICAgZGF0ZTogXCIwMy8xMi8yMDE5XCIsXG4gICAgICBtYW5uZXJPZkRlYXRoOiBcIlNob3RcIixcbiAgICAgIGFybWVkOiBcIlVuYXJtZWRcIixcbiAgICAgIGFnZTogMjYsXG4gICAgICBzZXg6IFwiRmVtYWxlXCIsXG4gICAgICBsb2NhdGlvbjogXCJMb3Vpc3ZpbGxlLCBLWVwiLFxuICAgICAgZmxlZWluZzogXCJOb3QgZmxlZWluZ1wiLFxuICAgICAgYm9keUNhbWVyYTogXCJObyBib2R5IGNhbWVyYVwiXG4gICAgfSxcblxuICAgIHtcbiAgICAgIG5hbWU6IFwiQ2hyaXMgRS5cIixcbiAgICAgIGRhdGU6IFwiMDMvMTYvMjAyMFwiLFxuICAgICAgbWFubmVyT2ZEZWF0aDogXCJTaG90XCIsXG4gICAgICBhcm1lZDogXCJVbmFybWVkXCIsXG4gICAgICBhZ2U6IDQ1LFxuICAgICAgc2V4OiBcIk1hbGVcIixcbiAgICAgIGxvY2F0aW9uOiBcIkRldHJvaXQsIE1JXCIsXG4gICAgICBmbGVlaW5nOiBcIk5vdCBmbGVlaW5nXCIsXG4gICAgICBib2R5Q2FtZXJhOiBcIk5vIGJvZHkgY2FtZXJhXCJcbiAgICB9XG4gIF07XG5cbiAgbGV0IGN1cnJlbnRQcm9maWxlID0gMDtcblxuICBsZXQgc3dhcHBlZCA9IG5ldyBTZXQoKTtcbiAgbGV0IHN3YXBwaW5nID0gZmFsc2U7XG4gIGxldCBzd2FwSW50ZXJ2YWw7XG5cbiAgbGV0IGFuaW1hdGlvbkR1cmF0aW9uID0gMTAwO1xuICBsZXQgYW5pbWF0aW9uRGltZW5zaW9uID0gXCJ5XCI7XG5cbiAgb25Nb3VudCgoKSA9PiB7XG4gICAgc3dhcEludGVydmFsID0gc2V0SW50ZXJ2YWwoYXN5bmMgKCkgPT4ge1xuICAgICAgc3dhcHBlZCA9IG5ldyBTZXQoKTtcblxuICAgICAgY29uc3QgbmV4dFByb2ZpbGUgPSAoY3VycmVudFByb2ZpbGUgKyAxKSAlIHByb2ZpbGVzLmxlbmd0aDtcblxuICAgICAgc3dhcHBpbmcgPSBcIm5hbWVcIjtcbiAgICAgIGF3YWl0IGRlbGF5KGFuaW1hdGlvbkR1cmF0aW9uKTtcbiAgICAgIHN3YXBwZWQuYWRkKFwibmFtZVwiKTtcblxuICAgICAgZm9yIChjb25zdCBmaWVsZCBvZiBmaWVsZHMpIHtcbiAgICAgICAgc3dhcHBpbmcgPSBmaWVsZC5rZXk7XG4gICAgICAgIGF3YWl0IGRlbGF5KGFuaW1hdGlvbkR1cmF0aW9uICogMC45KTtcbiAgICAgICAgc3dhcHBlZC5hZGQoZmllbGQua2V5KTtcbiAgICAgIH1cblxuICAgICAgY3VycmVudFByb2ZpbGUgPSBuZXh0UHJvZmlsZTtcbiAgICAgIHN3YXBwaW5nID0gZmFsc2U7XG4gICAgfSwgNDUwMCk7XG4gIH0pO1xuXG4gIG9uRGVzdHJveSgoKSA9PiB7XG4gICAgY2xlYXJJbnRlcnZhbChzd2FwSW50ZXJ2YWwpO1xuICB9KTtcblxuICAkOiBwcm9maWxlID0gcHJvZmlsZXNbY3VycmVudFByb2ZpbGVdO1xuICAkOiBuZXh0UHJvZmlsZSA9IHByb2ZpbGVzWyhjdXJyZW50UHJvZmlsZSArIDEpICUgcHJvZmlsZXMubGVuZ3RoXTtcblxuICBjb25zdCBnZXRGaWVsZCA9IChzd2FwcGVkLCBzd2FwcGluZywgcHJvZmlsZSwgbmV4dFByb2ZpbGUsIGtleSkgPT4ge1xuICAgIHJldHVybiBzd2FwcGluZyA9PT0gZmFsc2UgfHwgIXN3YXBwZWQuaGFzKGtleSlcbiAgICAgID8gcHJvZmlsZVtrZXldXG4gICAgICA6IG5leHRQcm9maWxlW2tleV07XG4gIH07XG5cbiAgY29uc3QgZmllbGRzID0gW1xuICAgIHsgbmFtZTogXCJEYXRlXCIsIGtleTogXCJkYXRlXCIgfSxcbiAgICB7IG5hbWU6IFwiTWFubmVyIG9mIERlYXRoXCIsIGtleTogXCJtYW5uZXJPZkRlYXRoXCIgfSxcbiAgICB7IG5hbWU6IFwiQXJtZWRcIiwga2V5OiBcImFybWVkXCIgfSxcbiAgICB7IG5hbWU6IFwiQWdlXCIsIGtleTogXCJhZ2VcIiB9LFxuICAgIHsgbmFtZTogXCJTZXhcIiwga2V5OiBcInNleFwiIH0sXG4gICAgeyBuYW1lOiBcIkxvY2F0aW9uXCIsIGtleTogXCJsb2NhdGlvblwiIH0sXG4gICAgeyBuYW1lOiBcIkZsZWVpbmcgdGhlIFNjZW5lXCIsIGtleTogXCJmbGVlaW5nXCIgfSxcbiAgICB7IG5hbWU6IFwiQm9keSBDYW1lcmFcIiwga2V5OiBcImJvZHlDYW1lcmFcIiB9XG4gIF07XG48L3NjcmlwdD5cblxuPGRpdiB7c3R5bGV9IGNsYXNzPVwiYm9yZGVyLTIgYm9yZGVyLXRhbiB7JCRwcm9wcy5jbGFzcyB8fCAnJ30gcC0xMiBpdGVtcy1zdGFydFwiPlxuICA8aDIgc3R5bGU9XCJoZWlnaHQ6IDEuNGVtXCIgY2xhc3M9XCJ0ZXh0LTR4bCBmb250LWJvbGRcIj5cbiAgICB7I2lmIHN3YXBwaW5nICE9PSAnbmFtZSd9XG4gICAgICA8c3BhblxuICAgICAgICBjbGFzcz1cImlubGluZS1ibG9ja1wiXG4gICAgICAgIGluOmZseT17eyBkdXJhdGlvbjogYW5pbWF0aW9uRHVyYXRpb24sIFthbmltYXRpb25EaW1lbnNpb25dOiAyMCB9fVxuICAgICAgICBvdXQ6Zmx5PXt7IGR1cmF0aW9uOiBhbmltYXRpb25EdXJhdGlvbiwgW2FuaW1hdGlvbkRpbWVuc2lvbl06IC0yMCB9fT5cbiAgICAgICAge2dldEZpZWxkKHN3YXBwZWQsIHN3YXBwaW5nLCBwcm9maWxlLCBuZXh0UHJvZmlsZSwgJ25hbWUnKX1cbiAgICAgIDwvc3Bhbj5cbiAgICB7L2lmfVxuICA8L2gyPlxuICB7I2VhY2ggZmllbGRzIGFzIGZpZWxkIChmaWVsZC5uYW1lKX1cbiAgICA8cCBjbGFzcz1cInRleHQtMnhsIG10LTRcIj5cbiAgICAgIDxzcGFuIGNsYXNzPVwibXItMlwiPntmaWVsZC5uYW1lfTo8L3NwYW4+XG5cbiAgICAgIHsjaWYgc3dhcHBpbmcgIT09IGZpZWxkLmtleX1cbiAgICAgICAgPHNwYW5cbiAgICAgICAgICBpbjpmbHk9e3sgZHVyYXRpb246IGFuaW1hdGlvbkR1cmF0aW9uLCBbYW5pbWF0aW9uRGltZW5zaW9uXTogMTUgfX1cbiAgICAgICAgICBvdXQ6Zmx5PXt7IGR1cmF0aW9uOiBhbmltYXRpb25EdXJhdGlvbiwgW2FuaW1hdGlvbkRpbWVuc2lvbl06IC0xNSB9fVxuICAgICAgICAgIGNsYXNzPVwidGV4dC1icm93bi1ncmF5IGlubGluZS1ibG9ja1wiPlxuICAgICAgICAgIHtnZXRGaWVsZChzd2FwcGVkLCBzd2FwcGluZywgcHJvZmlsZSwgbmV4dFByb2ZpbGUsIGZpZWxkLmtleSl9XG4gICAgICAgIDwvc3Bhbj5cbiAgICAgIHsvaWZ9XG4gICAgPC9wPlxuICB7L2VhY2h9XG48L2Rpdj5cbiIsImV4cG9ydCBjb25zdCBkZWxheSA9IChhbW91bnQ6IG51bWJlcikgPT4ge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUpID0+IHtcbiAgICByZXR1cm4gc2V0VGltZW91dChyZXNvbHZlLCBhbW91bnQpO1xuICB9KTtcbn07XG4iXSwic291cmNlUm9vdCI6IiJ9